version: "3.4"

services:

  neural:
    build:
      context: ./main_api
    restart: unless-stopped
    ports:
      - ${DOCKER_NEURAL_PORT:-8015}:80
    command: bash -c "make run"
    env_file:
      - .env
    volumes:
      - ./main_api:/app
      - ./data:/data
    environment:
      - MAX_WORKERS=1

  models_api:
    build:
      context: ./models_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${DOCKER_NEURAL_MODELS_PORT:-8016}:80
    volumes:
      - ./models_api:/app
      - ./models:/models
      - ./data:/data
    environment:
      - MAX_WORKERS=1

  transformers:
    build:
      context: ./transformers
      dockerfile: Dockerfile
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - ${DOCKER_TRANSFORMERS_PORT:-8017}:8000
    volumes:
      - ./transformers:/app
      - ./models:/models
