version: "3.4"

services:

  neural:
    build:
      context: ./main_api
    restart: unless-stopped
    ports:
      - ${DOCKER_NEURAL_PORT:-8015}:80
    command: bash -c "make run"
    env_file:
      - .env
    volumes:
      - ./main_api:/app
      - ./data:/data
    environment:
      - MAX_WORKERS=1

  models_api:
    build:
      context: ./models_api
    restart: unless-stopped
    ports:
      - ${DOCKER_NEURAL_MODELS_PORT:-8016}:80
    volumes:
      - ./models_api:/app
      - ./models:/models
      - ./data:/data
    environment:
      - MAX_WORKERS=1
