name: epigraphdb_neural_processing
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - black
  - flake8
  - autoflake
  - mypy
  - isort
  - jedi
  - jupyterlab
  - matplotlib
  - nodejs
  - numpy
  - pandas
  - seaborn
  - requests
  - spacy=3.0.6
  - textacy
  - environs
  - loguru
  - icecream
  - pydash
  - pip
  - pip:
    - nb_black
    - scispacy==0.4
